### ISSUE TITLE
Disable installation of plugin on JDK < 11

### ISSUE THREAD

**Issue by jkovalsky** [moacirrf/nb-java-decompiler#32]
Similarly to issue #[178](https://github.com/funfried/externalcodeformatter_for_netbeans/issues/178) in External Formatter plugin it would be good to disable installation of this decompiler plugin on JDKs older than required version 11. Please see [this example in module manifest](https://github.com/apache/netbeans/blob/master/java/lib.nbjshell9/manifest.mf#L8) for how to do that.

**Comment by moacirrf** [comment]
Hi
I will change manifest
thank you!
